r"""
===========================
Parametric Portfolio Policy
===========================

This tutorial shows how to map asset characteristics directly to portfolio weights
with :class:`~skfolio.optimization.ParametricPortfolioPolicy`, following Brandt,
Santa-Clara and Valkanov (2009) [1]_.

The classical pipeline forecasts expected returns and a covariance matrix from
the characteristics, then optimizes. A parametric portfolio policy skips the
forecasting step. The weight of each asset is its benchmark weight plus a linear
tilt in its cross-sectionally demeaned characteristics:

.. math::

    w_{t,i} = b_{t,i} + \frac{1}{N_t} \theta^\top \tilde{z}_{t,i}

and the few coefficients :math:`\theta` are chosen to maximize the investor's
average realized utility over the sample:

.. math::

    \max_{\theta} \; \frac{1}{T} \sum_{t} u\left(\sum_{i} w_{t,i} \, r_{t+1,i}\right)

with a CRRA utility of risk aversion :math:`\gamma`. Because the portfolio return
is linear in :math:`\theta` and the utility is concave, the problem is concave and
solved exactly by Newton's method, whatever the number of assets.

We fit a policy on size, value and momentum, inspect the coefficients and the
weights, and evaluate it out of sample against its value-weighted benchmark and
an equal-weighted portfolio.
"""

# %%
# Data
# ====
# We use a synthetic characteristics panel generated by
# :func:`~skfolio.datasets.make_synthetic_characteristics`, stored in an
# :class:`~skfolio.containers.AssetPanel` (see the
# :ref:`Factor Models <factor_models>` user guide for the container and the
# descriptors). The asset returns are extracted in the standard skfolio format:
import numpy as np
from plotly.io import show

from skfolio import Population
from skfolio.datasets import make_synthetic_characteristics
from skfolio.descriptor import BookToPrice, EWMomentum, LogMarketCap
from skfolio.factor_exposure import FixedWeightedFactor
from skfolio.model_selection import WalkForward, cross_val_predict
from skfolio.optimization import ParametricPortfolioPolicy

panel = make_synthetic_characteristics(
    n_assets=300, n_observations=1500, random_state=0
)
X = panel.to_dataframe(fields="returns")
X.tail()

# %%
# Characteristics
# ===============
# The characteristics are built with the same factor exposure estimators as the
# :class:`~skfolio.prior.CharacteristicsFactorModel`. Each
# :class:`~skfolio.factor_exposure.FixedWeightedFactor` winsorizes and standardizes
# its descriptor cross-sectionally, so the coefficients are comparable across
# characteristics:
characteristics = [
    ("size", FixedWeightedFactor(descriptors=[("log_mcap", LogMarketCap())])),
    ("value", FixedWeightedFactor(descriptors=[("book_to_price", BookToPrice())])),
    ("momentum", FixedWeightedFactor(descriptors=[("momentum", EWMomentum())])),
]

# %%
# Policy
# ======
# We fit the policy with the paper's risk aversion of 5 and a value-weighted
# benchmark (`benchmark_mcap_power=1`). `fit` takes the returns `X` and the panel
# as `characteristics`:
model = ParametricPortfolioPolicy(
    characteristics_exposures=characteristics,
    risk_aversion=5.0,
    benchmark_mcap_power=1.0,
)
model.fit(X, characteristics=panel)

# %%
# The fitted coefficients :math:`\theta` are the whole policy. A positive
# coefficient overweights assets with a high value of that characteristic relative
# to the benchmark:
for name, coef in zip(model.characteristic_names_, model.coef_, strict=True):
    print(f"{name:>10}: {coef:+.3f}")

# %%
# The average utility of the policy is compared with the benchmark's, and the
# solver reports its number of Newton iterations:
print(f"Policy utility:    {model.utility_:.6f}")
print(f"Benchmark utility: {model.benchmark_utility_:.6f}")
print(f"Newton iterations: {model.n_iter_}")

# %%
# Weights
# =======
# `weights_` are the policy weights at the last observation, ready for the next
# rebalancing, and `weights_history_` holds the in-sample weight path. The tilt is
# self-financing, so the weights sum to one at every observation. Weights can be
# negative: the policy is long-short around its benchmark.
print(f"Sum of weights: {model.weights_.sum():.6f}")
print(f"Short exposure: {model.weights_[model.weights_ < 0].sum():+.3f}")
print(f"Largest weight: {model.weights_.max():.3f}")

# %%
# The turnover of the in-sample path shows how much the characteristics move the
# portfolio from one observation to the next:
history = model.weights_history_
valid = ~np.isnan(history).all(axis=1)
turnover = np.abs(np.diff(history[valid], axis=0)).sum(axis=1)
print(f"Mean one-way turnover per observation: {turnover.mean():.3%}")

# %%
# Out-of-Sample Evaluation
# ========================
# We evaluate the policy with a walk-forward backtest using
# :func:`~skfolio.model_selection.cross_val_predict`: the policy is refitted on the
# previous two years of data and applied over the following month, and the panel
# is passed through `params` so that each fold receives the matching
# characteristics.
#
# Setting `max_iter=0` keeps :math:`\theta = 0`, which gives the benchmark itself
# under the same rebalancing and the same eligible universe: the value-weighted
# benchmark with `benchmark_mcap_power=1` and an equal-weighted portfolio with
# `benchmark_mcap_power=0`.
cv = WalkForward(train_size=2 * 252, test_size=21)

pred_policy = cross_val_predict(
    model, X, cv=cv, params={"characteristics": panel}, n_jobs=-1
)
pred_policy.name = "Parametric Policy"

value_weighted = ParametricPortfolioPolicy(
    characteristics_exposures=characteristics, max_iter=0, benchmark_mcap_power=1.0
)
pred_value_weighted = cross_val_predict(
    value_weighted, X, cv=cv, params={"characteristics": panel}, n_jobs=-1
)
pred_value_weighted.name = "Value-Weighted Benchmark"

equal_weighted = ParametricPortfolioPolicy(
    characteristics_exposures=characteristics, max_iter=0, benchmark_mcap_power=0.0
)
pred_equal_weighted = cross_val_predict(
    equal_weighted, X, cv=cv, params={"characteristics": panel}, n_jobs=-1
)
pred_equal_weighted.name = "Equal-Weighted"

population = Population([pred_policy, pred_value_weighted, pred_equal_weighted])
population.summary()

# %%
# The cumulative returns of the three portfolios:
fig = population.plot_cumulative_returns()
show(fig)

# %%
# |
#
# Risk Aversion
# =============
# The risk aversion :math:`\gamma` sets how the policy trades the mean of the
# realized return path against its variance and tail. A low :math:`\gamma` pushes
# the coefficients towards the return-seeking tilts, a high :math:`\gamma`
# towards the variance-reducing ones, so the in-sample volatility of the policy
# falls as :math:`\gamma` rises:
returns = X.to_numpy()
print(f"{'gamma':>5} {'size':>8} {'value':>8} {'momentum':>9} {'volatility':>11}")
for gamma in [2, 5, 10, 20]:
    policy = ParametricPortfolioPolicy(
        characteristics_exposures=characteristics, risk_aversion=gamma
    ).fit(X, characteristics=panel)
    # In-sample policy return path: weights at t applied to returns at t + 1
    weights = np.nan_to_num(policy.weights_history_[:-1])
    path = np.nansum(weights * returns[1:], axis=1)
    volatility = path.std() * np.sqrt(252)
    print(
        f"{gamma:>5} "
        + " ".join(f"{c:>8.3f}" for c in policy.coef_)
        + f" {volatility:>11.2%}"
    )

# %%
# Conclusion
# ==========
# A parametric portfolio policy compresses the portfolio choice into a handful of
# interpretable coefficients, one per characteristic, and fits them on the
# objective that matters, the investor's realized utility, without estimating
# expected returns or a covariance matrix. It reuses skfolio's
# :class:`~skfolio.containers.AssetPanel` and factor exposure estimators, so any
# descriptor or transformation available for the characteristics factor model can
# be used as a policy characteristic, and it plugs into the standard
# :ref:`model selection <model_selection>` tools for backtesting and tuning.
#
# References
# ==========
# .. [1] "Parametric Portfolio Policies: Exploiting Characteristics in the
#        Cross-Section of Equity Returns".
#        Brandt, M. W., Santa-Clara, P., & Valkanov, R. (2009).
#        The Review of Financial Studies, 22(9), 3411-3447.
