from __future__ import annotations

from collections.abc import Iterator
from types import SimpleNamespace

import numpy as np
import pytest

from skfolio.utils.tools import (
    _call_estimator,
    apply_window_size,
    args_names,
    bisection,
    deduplicate_names,
    default_asset_names,
    format_measure,
    half_life_to_decay_factor,
    input_to_array,
    safe_indexing,
    safe_split,
    validate_input_list,
)


class _RecordingEstimator:
    def __init__(self):
        self.calls = []

    def fit(self, X, y=None, **kwargs):
        self.calls.append(("fit", X, y, kwargs))
        return "fit_result"

    def partial_fit(self, X, y=None, **kwargs):
        self.calls.append(("partial_fit", X, y, kwargs))
        return "partial_fit_result"


# Generated by CodiumAI
class TestArgsNames:
    #  Returns a list of argument names for a given function.
    def test_returns_argument_names(self):
        # Define a function with arguments
        def my_function(arg1, arg2, arg3):
            pass

        # Call the args_names function
        result = args_names(my_function)

        # Check if the result is a list
        assert isinstance(result, list)

        # Check if the result contains the correct argument names
        assert result == ["arg1", "arg2", "arg3"]


class TestInputToArray:
    #  Convert a dictionary with asset names and values to a numpy array of shape (n_assets) when dim=1.
    def test_convert_dict_to_array_dim_1(self):
        items = {"asset1": 1, "asset2": 2, "asset3": 3}
        n_assets = 3
        fill_value = 0
        dim = 1
        assets_names = np.array(["asset1", "asset2", "asset3"])
        name = "items"

        expected_result = np.array([1, 2, 3])

        result = input_to_array(items, n_assets, fill_value, dim, assets_names, name)

        assert np.array_equal(result, expected_result)

    #  Raise a ValueError if items is a dictionary and assets_names is not provided.
    def test_raise_value_error_no_assets_names(self):
        items = {"asset1": 1, "asset2": 2, "asset3": 3}
        n_assets = 3
        fill_value = 0
        dim = 1
        assets_names = None
        name = "items"

        with pytest.raises(ValueError):
            input_to_array(items, n_assets, fill_value, dim, assets_names, name)


# Generated by CodiumAI
class TestFormatMeasure:
    #  Formats a positive float number without decimal places correctly.
    def test_positive_float_no_decimal(self):
        result = format_measure(10.0)
        assert result == "10.00"

    #  Formats a float number with the maximum number of decimal places correctly.
    def test_float_maximum_decimal(self):
        result = format_measure(3.141592653589793)
        assert result == "3.14"

    #  Formats a float number with the minimum number of decimal places correctly.
    def test_float_minimum_decimal(self):
        result = format_measure(0.123456)
        assert result == "0.12"


# Generated by CodiumAI
class TestBisection:
    #  The function receives a list of numpy arrays and returns an iterator.
    def test_returns_iterator(self):
        arr = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]
        result = bisection(arr)
        assert isinstance(result, Iterator)

    #  The function works correctly for empty arrays.
    def test_empty_arrays(self):
        arr = []
        result = list(bisection(arr))
        assert result == []

    #  The function works correctly for arrays with only one element.
    def test_single_element_array(self):
        arr = [np.array([1])]
        result = list(bisection(arr))
        assert result == []


# Generated by CodiumAI
class TestSafeIndexing:
    #  Returns the entire data if indices is None.
    def test_returns_entire_data_if_indices_is_none(self):
        X = np.array([1, 2, 3, 4, 5])
        indices = None
        result = safe_indexing(X, indices)
        assert np.array_equal(result, X)


# Generated by CodiumAI
class TestSafeSplit:
    #  Returns X_subset and y_subset when given valid inputs.
    def test_valid_inputs(self):
        # Arrange
        X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        y = np.array([1, 2, 3])
        indices = np.array([0, 2])
        axis = 0

        # Act
        X_subset, y_subset = safe_split(X, y, indices=indices, axis=axis)

        # Assert
        np.testing.assert_array_equal(X_subset, np.array([[1, 2, 3], [7, 8, 9]]))
        np.testing.assert_array_equal(y_subset, np.array([1, 3]))


# Generated by CodiumAI


class TestDefaultAssetNames:
    #  Returns an ndarray of str with length equal to n_assets.
    def test_returns_ndarray_with_length_equal_to_n_assets(self):
        n_assets = 5
        result = default_asset_names(n_assets)
        assert isinstance(result, np.ndarray)
        assert len(result) == n_assets

    #  Raises TypeError when n_assets is not an integer.
    def test_raises_type_error_when_n_assets_is_not_an_integer(self):
        n_assets = "5"
        with pytest.raises(TypeError):
            default_asset_names(n_assets)


def test_deduplicate_names():
    names = ["blah", "blah2", "blah3", "blah", "blah"]
    names = deduplicate_names(names)
    assert names == ["blah", "blah2", "blah3", "blah_1", "blah_2"]


# Test with valid integer inputs.
def test_int_inputs_valid():
    items = [0, 2, 4]
    n_assets = 5
    # For integer inputs, assets_names is not used.
    result = validate_input_list(items, n_assets, assets_names=None, name="test_assets")
    assert result == [0, 2, 4]


# Test with an invalid integer (out of range).
def test_int_input_invalid_index():
    items = [0, 5]  # 5 is out of range for n_assets=5 (valid indices are 0-4)
    n_assets = 5
    with pytest.raises(ValueError, match="is not in"):
        validate_input_list(items, n_assets, assets_names=None, name="test_assets")


# Test with valid string inputs.
def test_string_inputs_valid():
    assets_names = np.array(["A", "B", "C", "D", "E"])
    items = ["A", "D"]
    n_assets = len(assets_names)
    result = validate_input_list(
        items, n_assets, assets_names=assets_names, name="test_assets"
    )
    # "A" corresponds to index 0, "D" corresponds to index 3.
    assert result == [0, 3]


# Test with strings when assets_names is None.
def test_string_inputs_no_assets_names():
    items = ["A", "B"]
    n_assets = 2
    with pytest.raises(ValueError, match="must input `X`"):
        validate_input_list(items, n_assets, assets_names=None, name="test_assets")


# Test with duplicate entries (order is preserved).
def test_duplicate_entries():
    assets_names = np.array(["X", "Y", "Z"])
    # Both integer and string (that converts to the same index) are provided.
    items = [1, "Y", 1, "Y"]
    n_assets = len(assets_names)
    with pytest.raises(ValueError, match="Duplicates found"):
        _ = validate_input_list(
            items, n_assets, assets_names=assets_names, name="test_assets"
        )


# Test with a mix of valid integers and valid strings.
def test_mixed_inputs():
    assets_names = np.array(["Asset1", "Asset2", "Asset3", "Asset4"])
    # "Asset3" corresponds to index 2 and integer 0 is valid.
    items = [0, "Asset3"]
    n_assets = len(assets_names)
    result = validate_input_list(
        items, n_assets, assets_names=assets_names, name="test_assets"
    )
    assert result == [0, 2]


def test_validate_input_list_raise():
    assets_names = np.array(["Asset1", "Asset2", "Asset3", "Asset4"])
    # "Asset3" corresponds to index 2 and integer 0 is valid.
    items = ["Asset3", "wrong name"]
    n_assets = len(assets_names)
    with pytest.raises(ValueError):
        _ = validate_input_list(
            items, n_assets, assets_names=assets_names, name="test_assets"
        )


class TestApplyWindowSize:
    """Tests for apply_window_size function."""

    def test_returns_last_n_observations_2d(self):
        """Test that the function returns the last window_size rows for a 2D array."""
        X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
        result = apply_window_size(X, window_size=3)
        expected = np.array([[5, 6], [7, 8], [9, 10]])
        np.testing.assert_array_equal(result, expected)

    def test_returns_last_n_observations_1d(self):
        """Test that the function returns the last window_size elements for a 1D array."""
        X = np.array([1, 2, 3, 4, 5])
        result = apply_window_size(X, window_size=2)
        expected = np.array([4, 5])
        np.testing.assert_array_equal(result, expected)

    def test_window_size_none_returns_full_array(self):
        """Test that window_size=None returns the original array unchanged."""
        X = np.array([[1, 2], [3, 4], [5, 6]])
        result = apply_window_size(X, window_size=None)
        np.testing.assert_array_equal(result, X)

    def test_window_size_equals_length_returns_full_array(self):
        """Test that window_size equal to array length returns the full array."""
        X = np.array([[1, 2], [3, 4], [5, 6]])
        result = apply_window_size(X, window_size=3)
        np.testing.assert_array_equal(result, X)

    def test_window_size_one_returns_last_row(self):
        """Test that window_size=1 returns only the last row."""
        X = np.array([[1, 2], [3, 4], [5, 6]])
        result = apply_window_size(X, window_size=1)
        expected = np.array([[5, 6]])
        np.testing.assert_array_equal(result, expected)

    def test_window_size_float_converted_to_int(self):
        """Test that a float window_size is converted to int."""
        X = np.array([1, 2, 3, 4, 5])
        result = apply_window_size(X, window_size=3.0)
        expected = np.array([3, 4, 5])
        np.testing.assert_array_equal(result, expected)

    def test_window_size_larger_than_observations(self):
        """Test that ValueError is raised when window_size exceeds array length."""
        X = np.array([[1, 2], [3, 4]])
        apply_window_size(X, window_size=5)

    def test_raises_error_window_size_zero(self):
        """Test that ValueError is raised when window_size is zero."""
        X = np.array([1, 2, 3])
        with pytest.raises(ValueError, match="must be a positive integer"):
            apply_window_size(X, window_size=0)

    def test_raises_error_window_size_negative(self):
        """Test that ValueError is raised when window_size is negative."""
        X = np.array([1, 2, 3])
        with pytest.raises(ValueError, match="must be a positive integer"):
            apply_window_size(X, window_size=-1)

    def test_raises_error_window_size_invalid_type(self):
        """Test that ValueError is raised when window_size cannot be converted to int."""
        X = np.array([1, 2, 3])
        with pytest.raises(ValueError, match="must be an integer or convertible"):
            apply_window_size(X, window_size="invalid")

    def test_raises_error_window_size_list(self):
        """Test that ValueError is raised when window_size is a list."""
        X = np.array([1, 2, 3])
        with pytest.raises(ValueError, match="must be an integer or convertible"):
            apply_window_size(X, window_size=[1, 2])


class TestHalfLifeToDecayFactor:
    """Tests for half_life_to_decay_factor function."""

    def test_known_values(self):
        """Test conversion with known half-life to decay factor values."""
        # half_life = 40 -> decay_factor ≈ 0.9828
        np.testing.assert_almost_equal(half_life_to_decay_factor(40), 0.9828, decimal=4)
        # half_life = 23 -> decay_factor ≈ 0.9703
        np.testing.assert_almost_equal(half_life_to_decay_factor(23), 0.9703, decimal=4)
        # half_life = 11 -> decay_factor ≈ 0.9390
        np.testing.assert_almost_equal(half_life_to_decay_factor(11), 0.9390, decimal=4)
        # half_life = 6 -> decay_factor ≈ 0.8909
        np.testing.assert_almost_equal(half_life_to_decay_factor(6), 0.8909, decimal=4)

    def test_formula_correctness(self):
        """Test that the formula λ = 2^(-1/half_life) is correctly implemented."""
        for half_life in [1, 5, 10, 20, 50, 100]:
            expected = 2.0 ** (-1.0 / half_life)
            result = half_life_to_decay_factor(half_life)
            np.testing.assert_almost_equal(result, expected)

    def test_half_life_one_gives_half_decay(self):
        """Test that half_life=1 gives decay_factor=0.5 (weight halves each period)."""
        np.testing.assert_almost_equal(half_life_to_decay_factor(1), 0.5)

    def test_large_half_life_approaches_one(self):
        """Test that large half-life values give decay factors close to 1."""
        result = half_life_to_decay_factor(1000)
        assert 0.999 < result < 1.0

    def test_small_half_life_approaches_zero(self):
        """Test that small half-life values give decay factors closer to 0."""
        result = half_life_to_decay_factor(0.1)
        assert 0.0 < result < 0.1

    def test_raises_error_zero_half_life(self):
        """Test that ValueError is raised when half_life is zero."""
        with pytest.raises(ValueError, match="must be positive"):
            half_life_to_decay_factor(0)

    def test_raises_error_negative_half_life(self):
        """Test that ValueError is raised when half_life is negative."""
        with pytest.raises(ValueError, match="must be positive"):
            half_life_to_decay_factor(-10)

    def test_inverse_relationship(self):
        """Test that decay_factor from half_life can be inverted back."""
        for half_life in [5, 10, 20, 40, 100]:
            decay_factor = half_life_to_decay_factor(half_life)
            # Inverse formula: half_life = -ln(2) / ln(decay_factor)
            recovered_half_life = -np.log(2) / np.log(decay_factor)
            np.testing.assert_almost_equal(recovered_half_life, half_life)


class TestCallEstimator:
    @pytest.mark.parametrize("method", ["fit", "partial_fit"])
    def test_calls_method_with_routed_and_extra_params(self, method):
        estimator = _RecordingEstimator()
        X = np.array([[1.0, 2.0], [3.0, 4.0]])
        y = np.array([1.0, 0.0])
        routed_params = SimpleNamespace(
            fit={"sample_weight": np.array([0.2, 0.8])},
            partial_fit={"active_mask": np.array([[True, True], [True, False]])},
        )
        extra_params = {"window_size": 20}

        result = _call_estimator(
            estimator,
            method,
            X,
            y,
            routed_params=routed_params,
            extra_params=extra_params,
        )

        assert result == f"{method}_result"
        call_method, call_X, call_y, call_kwargs = estimator.calls[-1]
        assert call_method == method
        np.testing.assert_array_equal(call_X, X)
        np.testing.assert_array_equal(call_y, y)
        assert call_kwargs["window_size"] == 20
        if method == "fit":
            np.testing.assert_array_equal(
                call_kwargs["sample_weight"], routed_params.fit["sample_weight"]
            )
        else:
            np.testing.assert_array_equal(
                call_kwargs["active_mask"], routed_params.partial_fit["active_mask"]
            )

    def test_raises_on_conflicting_routed_and_extra_params(self):
        estimator = _RecordingEstimator()
        routed_params = SimpleNamespace(fit={"sample_weight": np.array([0.5, 0.5])})

        with pytest.raises(ValueError, match="Conflicting parameters for 'fit'"):
            _call_estimator(
                estimator,
                "fit",
                np.array([[1.0], [2.0]]),
                routed_params=routed_params,
                extra_params={"sample_weight": np.array([0.2, 0.8])},
            )

    def test_raises_on_missing_partial_fit(self):
        estimator = object()

        with pytest.raises(TypeError, match="does not implement partial_fit"):
            _call_estimator(estimator, "partial_fit", np.array([[1.0], [2.0]]))

    def test_raises_on_missing_method(self):
        estimator = _RecordingEstimator()

        with pytest.raises(TypeError, match="does not implement 'transform'"):
            _call_estimator(estimator, "transform", np.array([[1.0], [2.0]]))
