r"""
==============================
Characteristics Factor Model
==============================

This tutorial shows how to build a characteristics-based cross-sectional factor
model with :class:`~skfolio.prior.CharacteristicsFactorModel`. The methodology
is covered in the :ref:`Factor Models <factor_models>` user guide.

A characteristics factor model builds factor exposures from point-in-time asset
characteristics (e.g. industry, market capitalization, book equity, analyst
estimates). It computes the exposures from the data and estimates the factor
returns at each date by cross-sectional regression of asset returns on the
lagged exposures:

.. math::

    r_t = B \, f_t + \epsilon_t

where :math:`B` is the factor exposure matrix, :math:`f_t` the factor returns
and :math:`\epsilon_t` the idiosyncratic returns.

The model then assembles the asset covariance forecast from the factor
covariance :math:`F`, estimated on the factor return series, and the
idiosyncratic covariance :math:`D`, estimated on the regression residuals:

.. math::

    \Sigma = B \, F \, B^\top + D

We build a model with 24 factors (1 global market factor, 10 industry factors
and 13 style factors from 29 descriptors), fit it on a synthetic panel, run its
diagnostics, evaluate its covariance forecast out of sample and tune its
hyperparameters.
"""

# %%
# Data
# ====
# We use a synthetic characteristics panel generated by
# :func:`~skfolio.datasets.make_synthetic_characteristics`. It includes late
# listings, delistings, holidays and missing characteristics.
# Asset characteristics come from commercial point-in-time datasets whose
# licences prohibit redistribution, so the gallery uses synthetic data to
# present the full API. For results on real data, see the
# :ref:`Factor Models <factor_models>` user guide.
import numpy as np
from plotly.io import show

from skfolio.datasets import make_synthetic_characteristics

panel = make_synthetic_characteristics(
    n_assets=500, n_observations=1500, random_state=0
)

# %%
# The panel is an :class:`~skfolio.containers.AssetPanel`, a container of
# point-in-time fields aligned on shared observation and asset axes of shape
# (n_observations, n_assets). See the :ref:`Asset Data Representation
# <asset_data_representation>` user guide for more details.
#
# Let's inspect the data with `to_dataframe`, which converts the panel to a
# pandas DataFrame:
panel.to_dataframe(output_format="long").head()

# %%
# Next, we summarize the panel structure with the `info` method:
print(panel.info())

# %%
# From the `info()` report:
#
# * The **Active Mask** identifies which asset-observation pairs are active.
#   90.3% of entries are active. The remainder are pre-listing and
#   post-delisting periods, visible in the asset-duration statistics.
# * The **Estimation Mask** selects the active pairs used to fit
#   cross-sectional statistics and regressions. 475 of the 500 assets
#   contribute to estimation, emulating a restricted estimation universe
#   (e.g. exclusions for data quality). Excluded assets still
#   receive exposures and forecasts.
# * **Field Coverage** reports missingness per field. Price, volume, shares
#   and market cap are fully populated on active entries, while the
#   forward-looking fields (`eps_ntm`, `dps_ntm`, `eps_ntm_std`) carry about
#   20% missing values, as with real analyst-estimate coverage.
# * `industry` is a categorical field with 10 levels.

# %%
# Factor Exposures
# ================
# We define each factor with a factor exposure estimator that transforms the
# panel fields into exposures (see :ref:`Factor Exposures
# <factor_model_factor_exposures>` in the user guide). Estimators carry a
# `family` attribute (`"market"`, `"industry"`, `"style"`) used for
# neutralization, zero-sum constraints and reporting.
#
# We first define the trading-day constants used for descriptor half-lives and
# lags throughout the tutorial:
week = 5
month = 21
quarter = 3 * month
half_year = 6 * month
year = 12 * month

# %%
# Global Factor
# -------------
# The global factor has unit exposure for every asset. With benchmark-weighted
# centering and the industry zero-sum constraint set below, its factor return
# captures the benchmark (market) return (see :ref:`Global Factor and
# Benchmark Portfolio <factor_model_global_factor>`):
from skfolio.factor_exposure import GlobalFactor

global_factor = GlobalFactor(family="market")

# %%
# Industry Factors
# ----------------
# Next, we build the industry factors as one-hot exposures from the
# `industry` categorical field, one factor per industry:
from skfolio.factor_exposure import OneHotCategoricalFactors

industry_factors = OneHotCategoricalFactors(category="industry", family="industry")

# %%
# Style Factors
# -------------
# Now we build the style factors with
# :class:`~skfolio.factor_exposure.FixedWeightedFactor` from one or more
# descriptors, each computed from panel fields (e.g.
# :class:`~skfolio.descriptor.BookToPrice` from `book_equity` and
# `market_cap`). The estimator winsorizes and z-scores each descriptor
# cross-sectionally, then combines the scores with the fixed weights
# (see :ref:`Descriptors <factor_model_descriptors>` and
# :ref:`Cross-Sectional Transformers
# <factor_model_cross_sectional_transformers>`). With
# `transform_by_group="industry"`, scoring happens within each industry,
# which makes style exposures orthogonal to the industry factors:
from skfolio.descriptor import (
    AssetsGrowthRate,
    AssetTurnover,
    BookLeverage,
    BookToPrice,
    CapexToAssetsChangeInIntensity,
    CashFlowToAssets,
    CashFlowToPrice,
    DebtToAssets,
    DividendToPrice,
    EarningsChangeToPrice,
    EarningsToPrice,
    EbitdaToEnterpriseValue,
    EWAmihudIlliquidity,
    EWMarketBeta,
    EWMomentum,
    EWResidualVolatility,
    EWShareTurnover,
    EWVolatility,
    ForwardEarningsToPrice,
    GrossMargin,
    GrossProfitability,
    IssuanceGrowthRate,
    LogMarketCap,
    MarketLeverage,
    ReturnOnAssets,
    ReturnOnEquity,
    SalesGrowthRate,
    SalesToPrice,
    ShareholderYield,
)
from skfolio.factor_exposure import DerivedFactor, FixedWeightedFactor

beta_factor = FixedWeightedFactor(
    descriptors=[("market_beta", EWMarketBeta(half_life=year))],
    transform_by_group="industry",
)

momentum_factor = FixedWeightedFactor(
    descriptors=[("momentum", EWMomentum(half_life=half_year, skip=month))],
    transform_by_group="industry",
)

size_factor = FixedWeightedFactor(
    descriptors=[("log_mcap", LogMarketCap())], transform_by_group="industry"
)

non_linear_size_factor = DerivedFactor(
    source="size", func=lambda x: x**3, transform_by_group="industry"
)

value_factor = FixedWeightedFactor(
    descriptors=[
        ("book_to_price", BookToPrice()),
        ("sales_to_price", SalesToPrice()),
        ("cash_flow_to_price", CashFlowToPrice()),
    ],
    weights=[0.8, 0.1, 0.1],
    transform_by_group="industry",
)

earnings_yield_factor = FixedWeightedFactor(
    descriptors=[
        ("fwd_earnings_to_price", ForwardEarningsToPrice()),
        ("earnings_to_price", EarningsToPrice()),
        ("enterprise_multiple", EbitdaToEnterpriseValue()),
    ],
    transform_by_group="industry",
)

growth_factor = FixedWeightedFactor(
    descriptors=[
        ("earnings_change_to_price", EarningsChangeToPrice(lag=year)),
        ("sales_growth", SalesGrowthRate(lag=year)),
    ],
    transform_by_group="industry",
)

profitability_factor = FixedWeightedFactor(
    descriptors=[
        ("asset_turnover", AssetTurnover()),
        ("gross_profitability", GrossProfitability()),
        ("gross_margin", GrossMargin()),
        ("return_on_assets", ReturnOnAssets()),
        ("return_on_equity", ReturnOnEquity()),
        ("cash_flow_to_assets", CashFlowToAssets()),
    ],
    transform_by_group="industry",
)

investment_factor = FixedWeightedFactor(
    descriptors=[
        ("asset_growth", AssetsGrowthRate(lag=year)),
        ("issuance_growth", IssuanceGrowthRate(lag=year)),
        ("capex_growth", CapexToAssetsChangeInIntensity(lag=year)),
    ],
    transform_by_group="industry",
)

dividend_yield_factor = FixedWeightedFactor(
    descriptors=[
        ("dividend_to_price", DividendToPrice()),
        ("shareholder_yield", ShareholderYield()),
    ],
    weights=[0.7, 0.3],
    transform_by_group="industry",
)

leverage_factor = FixedWeightedFactor(
    descriptors=[
        ("market_leverage", MarketLeverage()),
        ("debt_to_assets", DebtToAssets()),
        ("book_leverage", BookLeverage()),
    ],
    transform_by_group="industry",
)

liquidity_factor = FixedWeightedFactor(
    descriptors=[
        ("share_turnover", EWShareTurnover(half_life=quarter)),
        ("amihud_illiquidity", EWAmihudIlliquidity()),
    ],
    transform_by_group="industry",
)

volatility_factor = FixedWeightedFactor(
    descriptors=[
        ("vol", EWVolatility(half_life=quarter)),
        (
            "residual_vol",
            EWResidualVolatility(half_life=quarter, beta_half_life=quarter),
        ),
    ],
    transform_by_group="industry",
)

# %%
# The non-linear size factor is a
# :class:`~skfolio.factor_exposure.DerivedFactor` computed as the cube of the
# size exposure, capturing return patterns that differ between mid-caps and
# the extremes of the size spectrum. The momentum descriptor
# :class:`~skfolio.descriptor.EWMomentum` skips the most recent month
# (`skip=month`) to separate medium-term momentum from short-term reversal.

# %%
# Model Definition
# ================
# We now assemble the factors into a
# :class:`~skfolio.prior.CharacteristicsFactorModel`:
from skfolio.moments import EWMu, RegimeAdjustedEWCovariance
from skfolio.prior import CharacteristicsFactorModel, EmpiricalPrior

model = CharacteristicsFactorModel(
    factors=[
        ("market", global_factor),
        ("industry", industry_factors),
        ("beta", beta_factor),
        ("momentum", momentum_factor),
        ("size", size_factor),
        ("non_linear_size", non_linear_size_factor),
        ("value", value_factor),
        ("earnings_yield", earnings_yield_factor),
        ("growth", growth_factor),
        ("profitability", profitability_factor),
        ("investment", investment_factor),
        ("dividend_yield", dividend_yield_factor),
        ("leverage", leverage_factor),
        ("liquidity", liquidity_factor),
        ("volatility", volatility_factor),
    ],
    neutralize_against={
        "non_linear_size": ["size"],
        "volatility": ["beta"],
    },
    constrained_families=[("industry", None)],
    exposure_lag=1,
    inv_idio_variance_weight_shrinkage=0.5,
    factor_prior_estimator=EmpiricalPrior(
        covariance_estimator=RegimeAdjustedEWCovariance(
            half_life=half_year, corr_half_life=year, regime_half_life=month
        ),
        mu_estimator=EWMu(half_life=year),
    ),
    n_jobs=-1,
)

# %%
# Let's walk through the main parameters:
#
# * `neutralize_against` orthogonalizes the non-linear size exposure against
#   size and the volatility exposure against beta, keeping only the component
#   uncorrelated with the target factor (see :ref:`Neutralization
#   <factor_model_neutralization>`).
# * `constrained_families` applies a benchmark-weighted zero-sum constraint on
#   the industry factor returns. The one-hot industry exposures sum to the
#   market exposure, so without a constraint the regression design is
#   rank-deficient (see :ref:`Zero-Sum Constraints
#   <factor_model_zero_sum_constraints>`). With it, the market factor captures
#   the benchmark return and industry factors capture relative effects around
#   it.
# * `exposure_lag=1` regresses the returns over :math:`(t-1, t]` on exposures
#   measured at :math:`t-1`, avoiding look-ahead bias (see :ref:`Time
#   Alignment and Look-Ahead Bias <factor_model_time_alignment>`).
# * `inv_idio_variance_weight_shrinkage=0.5` blends square-root market-cap
#   regression weights with inverse-idiosyncratic-variance weights in a
#   two-pass feasible GLS (see :ref:`Regression Weights
#   <factor_model_regression_weights>`).
# * The factor prior estimates expected factor returns with an exponentially
#   weighted mean and the factor covariance with a regime-adjusted
#   exponentially weighted estimator (see :ref:`Factor Return Distribution
#   <factor_model_factor_return_distribution>`).

# %%
# Fitting
# =======
#
# Batch Fit
# ---------
# We fit the model on the panel. The `X` argument (asset returns defining
# the investment universe) is optional. When omitted, the investment universe
# equals the coverage universe:
model.fit(characteristics=panel)

# %%
# Descriptor warmup consumes the first year of observations (the longest lag
# in the model is one year, used by the growth and investment descriptors),
# plus one observation for the exposure lag, leaving 1,247 fitted
# observations out of 1,500.

# %%
# Online Learning
# ---------------
# The model also supports online learning (see :ref:`Online
# Learning <factor_model_online_learning>`). `partial_fit` appends new
# observations without refitting the history, and the result is identical to
# a batch `fit` on the concatenated data. The first call must provide enough
# history for the stacked descriptor and estimator warmups (see :ref:`Warmup
# Periods <factor_model_warmup>`), while later chunks can be as small as one
# observation. Let's refit the model on an initial warmup window, then feed
# it monthly chunks:
warmup = 2 * year + month
model.fit(characteristics=panel[:warmup])

for i in range(warmup, len(panel), month):
    model.partial_fit(characteristics=panel[i : i + month])

# %%
# Model Outputs
# =============
# Now let's look at what the fitted model produces. `return_distribution_`
# holds the :class:`~skfolio.prior.ReturnDistribution` consumed by all
# skfolio optimizations: expected returns `mu`, asset covariance `covariance`
# and asset return scenarios `returns`. Assets that are not investable at the last
# observation (e.g. delisted or still in warmup) carry NaN moments. Compatible
# optimizers solve on the investable subset and assign zero weight to the
# rest:
distribution = model.return_distribution_
print(f"mu shape: {distribution.mu.shape}")
print(f"covariance shape: {distribution.covariance.shape}")
print(f"scenarios shape: {distribution.returns.shape}")
print(f"investable assets: {np.isfinite(distribution.mu).sum()}")

# %%
# Next, we retrieve `factor_model_`, the :class:`~skfolio.prior.FactorModel`
# container holding the full decomposition: factor exposures, loading matrix,
# factor returns, expected factor returns and covariance, idiosyncratic
# returns, variances and covariance, regression and benchmark weights, plus
# the diagnostics used in the sections below. Its `summary` method reports
# per-factor statistics:
factor_model = model.factor_model_

factor_model.summary(families=["market", "style"])

# %%
# These are pure-factor returns. Each factor return is the cross-sectional
# regression coefficient for one unit of exposure, the return of a
# factor-mimicking portfolio with unit exposure to that factor and zero
# exposure to all others.

# %%
# Exposure Diagnostics
# ====================
# Now we check the conditioning of the exposure matrix (see
# :ref:`Exposure Diagnostics <factor_model_diagnostics>`). Strong collinearity
# between exposures inflates the variance of the estimated factor returns and
# makes attribution unstable. We start with the time-average pairwise
# exposure correlations:
fig = factor_model.plot_exposure_correlation()
fig.update_layout(height=700)

# %%
# The market exposure is constant (every asset has unit exposure), so its
# correlation row is uninformative and displays as zero. Market neutrality is
# instead guaranteed by benchmark-weighted centering: every exposure has a
# zero benchmark-weighted mean, so no factor carries net market exposure.
# The style-industry correlations are zero, the result of
# within-industry scoring
# (`transform_by_group="industry"`), and so are the volatility-beta and
# non-linear size-size correlations, the result of `neutralize_against`.
# Industry factors are slightly negatively correlated rather than
# uncorrelated. Each asset belongs to exactly one industry, so membership in
# one industry rules out membership in all others. Zero correlation would
# mean industry memberships are independent. The remaining style
# correlations reflect the correlated traits of the synthetic universe (e.g.
# value with leverage and earnings yield), with no redundant factors,
# consistent with the low mean variance inflation factors (`mean_vif`)
# reported in the summary table above.
#
# .. note::
#
#     For two one-hot exposures :math:`x` and :math:`y` with benchmark
#     weights :math:`p_x` and :math:`p_y`, the product :math:`xy` is always
#     zero, so the covariance
#     :math:`\mathbb{E}[xy] - \mathbb{E}[x]\mathbb{E}[y] = -p_x p_y` is
#     negative, giving a correlation of
#     :math:`-\sqrt{p_x p_y / ((1-p_x)(1-p_y))}`, about -0.11 for ten
#     industries of similar weight.

# %%
# Regression Diagnostics
# ======================
# Let's inspect the fit of the cross-sectional regressions with
# `cs_regression_scores`, which reports per-observation fit statistics:
factor_model.cs_regression_scores.mean()

# %%
factor_model.plot_cs_regression_scores(score="adjusted_r2", window=20)

# %%
# The mean :math:`R^2` is around 60%. The synthetic generator was
# parametrized with `systematic_variance_ratio=0.5`, so half of the
# cross-sectional return variance comes from the factor structure on average.
# The weighted regression sits above that average because its weights
# emphasize large-cap, low-idiosyncratic-variance assets, whose systematic
# share is higher. On real daily US equity data, the mean :math:`R^2`
# typically falls between 25% and 40% (see :ref:`Regression Diagnostics
# <factor_model_regression_diagnostics>` in the user guide). The synthetic
# universe is smaller and cleaner than a real one.
#
# Next, `plot_cs_regression_t_stat_exceedance_rate` shows how often each factor's
# t-statistic exceeds 2 in absolute value. A factor whose true coefficient is
# zero would exceed it about 5% of the time, so rates persistently above this
# reference identify factors that are repeatedly significant in the
# cross-section:
factor_model.plot_cs_regression_t_stat_exceedance_rate(families=["market", "style"])

# %%
# Factor Returns
# ==============
# Let's plot the estimated factor returns accumulated through time:
fig = factor_model.plot_factor_cumulative_returns(families=["market", "style"])
show(fig)

# %%
# |
#
# The market factor tracks the cumulative benchmark return, as expected from
# the benchmark-weighted centering and the industry zero-sum constraint.
# Among the style factors, momentum shows the largest cumulative return and
# the highest annualized Sharpe ratio in the summary table above. The
# synthetic generator assigns momentum a persistent premium, and the model
# recovers it from the cross-section of returns.

# %%
# Idiosyncratic Risk Calibration
# ==============================
# Now let's test the idiosyncratic volatility forecasts. The diagnostics use
# the standardized idiosyncratic returns
# :math:`z_{it} = u_{it} / \hat\sigma_{it}`. Under correct calibration,
# :math:`z` has cross-sectional standard deviation 1.0:
factor_model.idio_calibration_summary()

# %%
factor_model.plot_idio_calibration(window=20)

# %%
# The series oscillates around 1.0, so the idiosyncratic risk forecasts are
# correctly scaled. The `mean_tail_rate_3sigma` of about 0.5%, above the
# 0.27% Gaussian reference, reflects the fat tails of the idiosyncratic
# returns, a feature of real equity data reproduced by the generator through
# Student-t shocks.
#
# Let's now separate ranking power from calibration with `plot_idio_vol_ic`,
# which displays the Spearman correlation between predicted volatility and the
# next-period absolute idiosyncratic return. High values mean the model ranks
# cross-sectional volatility differences well, while the calibration series
# above tests their scale. Together they show that the idiosyncratic risk
# forecasts are both well ordered and well scaled:
factor_model.plot_idio_vol_ic()

# %%
# Information Coefficient
# =======================
# To close the in-sample diagnostics, let's measure the return-predictive
# power of the exposures with `exposure_ic_summary`, the cross-sectional rank
# correlation between factor exposures at :math:`t` and forward asset returns:
factor_model.exposure_ic_summary(families=["market", "style"])

# %%
factor_model.plot_cumulative_exposure_ic(families=["market", "style"])

# %%
# Here the yield-related factors (earnings
# yield, dividend yield) accumulate positive IC with hit rates above 52%,
# consistent with the positive premia assigned to them by the generator.
#
# The IC quantifies return-predictive power. In a risk model, factors are
# designed to forecast covariance, not expected returns.
# A factor can therefore be an excellent risk factor with an IC near zero, and
# a low IC is not a reason to discard it. The IC is mainly useful for
# evaluating alpha signals and factor premia, not for deciding whether a
# factor should remain in a risk model.

# %%
# Covariance Forecast Evaluation
# ==============================
# The diagnostics above are in-sample, and in-sample fit says little about
# forecast quality. We now evaluate the covariance forecast out of sample with
# :func:`~skfolio.model_selection.online_covariance_forecast_evaluation` (see
# :ref:`Covariance Forecast Evaluation
# <factor_model_covariance_forecast_evaluation>`). It walks forward through
# the data, compares each covariance forecast with the subsequently realized
# returns and reports calibration diagnostics.
#
# `X` are the asset returns in the standard skfolio format and
# `warmup_size` reserves two years plus one month for the estimator warmups
# (see :ref:`Warmup Periods <factor_model_warmup>`):
from skfolio.model_selection import online_covariance_forecast_evaluation

X = panel.to_dataframe(fields="returns")

evaluation = online_covariance_forecast_evaluation(
    model,
    X,
    params={"characteristics": panel},
    warmup_size=warmup,
    test_size=week,
)
evaluation.summary()

# %%
# The Mahalanobis ratio tests the full covariance structure and the diagonal
# ratio the individual asset variances, both with a 1.0 target. Values above
# 1.0 indicate underestimated risk and below 1.0 overestimated risk. The
# portfolio standardized returns test calibration along a portfolio direction,
# with `std` as the bias statistic, and the portfolio QLIKE scores the
# portfolio variance forecasts, lower being better.
evaluation.plot_calibration(diagnostics=["bias"])

# %%
# The bias statistic oscillates around its 1.0 target, and the summary table
# shows the Mahalanobis and diagonal calibration ratios close to 1.0 as well,
# so the risk forecasts are well calibrated across the sample.

# %%
# Hyperparameter Tuning
# =====================
# All model parameters, from descriptor half-lives to weighting powers and
# shrinkages, follow the scikit-learn convention and can be tuned with
# standard model-selection utilities.
# :class:`~skfolio.model_selection.OnlineGridSearch` evaluates each candidate
# in a single walk-forward pass (see :ref:`Hyperparameter Tuning
# <factor_model_hyper_parameter_tuning>`).
#
# Here we score the risk model directly on its covariance forecast with a
# QLIKE loss and tune the regime half-life of the factor covariance
# estimator. In `make_scorer`, `response_method=None` indicates a
# non-predictor estimator and `greater_is_better=False` a loss to minimize:
from skfolio.metrics import make_scorer, portfolio_variance_qlike_loss
from skfolio.model_selection import OnlineGridSearch

qlike_scorer = make_scorer(
    portfolio_variance_qlike_loss,
    greater_is_better=False,
    response_method=None,
)

search = OnlineGridSearch(
    estimator=model,
    param_grid={
        "factor_prior_estimator__covariance_estimator__regime_half_life": [
            10,
            21,
            63,
        ],
    },
    scoring=qlike_scorer,
    warmup_size=warmup,
    test_size=week,
)
search.fit(X, characteristics=panel)
print(search.best_params_)

# %%
# When the model is embedded in an optimizer, the same search can instead
# target portfolio-level scores (e.g. ratio measures) to tune the full
# pipeline, as shown in the user guide.

# %%
# Conclusion
# ==========
# We built a 24-factor characteristics factor model, verified its exposures
# and regressions, evaluated and tuned its risk forecasts out of sample, and
# updated it online. The fitted model is a prior estimator, so we can pass it
# to any skfolio optimizer through `prior_estimator`. It supplies expected
# returns, covariance, scenarios and factor exposures that can be constrained
# by name.
#
# The next tutorial builds a factor-constrained portfolio on top of this
# model and performs factor-level risk and performance attribution.
#
# .. seealso::
#       The :ref:`Factor Models <factor_models>` user guide covers the
#       methodology in depth, including portfolio construction, attribution
#       and alpha integration with this model.

# %%
# References
# ==========
# .. [1] B. Rosenberg, "Extra-Market Components of Covariance in Security
#    Returns", *Journal of Financial and Quantitative Analysis*, vol. 9, no. 2,
#    pp. 263-274 (1974). `doi:10.2307/2330104
#    <https://doi.org/10.2307/2330104>`_.
#
# .. [2] R. C. Grinold and R. N. Kahn, *Active Portfolio Management: A
#    Quantitative Approach for Producing Superior Returns and Controlling Risk*,
#    McGraw-Hill (1999).
#
# .. [3] G. A. Paleologo, *The Elements of Quantitative Investing*, Wiley
#    Finance (2025).
