name: dependency-review

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          allow-licenses: MIT,BSD-3-Clause,BSD-2-Clause,Apache-2.0,ISC
          comment-summary-in-pr: true


