name: Deploy Documentation

on:
  workflow_run:
    workflows: ["Semantic Release"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.gh_pages_deployment.outputs.page_url }}
    concurrency: release

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -r pyproject.toml --extra docs

      - name: Build Sphinx Docs
        working-directory: ./docs
        run: uv run sphinx-build . _build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Documentation Site Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build

      - name: Deploy Sphinx Docs to GitHub Pages
        id: gh_pages_deployment
        uses: actions/deploy-pages@v4
